# Generated by Django 4.1.2 on 2022-10-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tig_id', models.IntegerField(default='-1')),
                ('type', models.IntegerField(default='0')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(blank=True, default='', max_length=100)),
                ('category', models.IntegerField(default='-1')),
                ('price', models.FloatField(default='0')),
                ('sale', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default='0')),
                ('stock', models.IntegerField(default='0')),
                ('userId', models.CharField(blank=True, default=' ', max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
