# Generated by Django 4.1.2 on 2022-10-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
