# Generated by Django 4.1.2 on 2022-10-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_infotransaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infotransaction',
            old_name='price',
            new_name='buyPrice',
        ),
        migrations.AddField(
            model_name='infotransaction',
            name='sellPrice',
            field=models.FloatField(default='0'),
        ),
    ]
