# Generated by Django 4.1.2 on 2022-10-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoproduct',
            name='userId',
        ),
    ]
