# Generated by Django 4.1.2 on 2022-10-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_infoproduct_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproduct',
            name='userId',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
    ]
