# Generated by Django 4.1.2 on 2022-10-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0005_productofcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofcategory',
            name='category',
            field=models.IntegerField(default='-1'),
        ),
    ]
